'use server';
/**
 * @fileOverview Provides an AI-powered yield insight tool for DeFi investors.
 *
 * - aiPoweredYieldInsight - A function that provides personalized strategies to optimize TOT/TOF yield.
 * - AiPoweredYieldInsightInput - The input type for the aiPoweredYieldInsight function.
 * - AiPoweredYieldInsightOutput - The return type for the aiPoweredYieldInsight function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiPoweredYieldInsightInputSchema = z.object({
  walletAddress: z.string().describe('The user\'s blockchain wallet address.'),
  language: z.enum(['en', 'zh']).default('en').describe('The preferred language for the response.'),
  totBalance: z.number().describe('Current balance of TOT tokens.'),
  tofBalance: z.number().describe('Current balance of TOF tokens.'),
  usdtBalance: z.number().describe('Current balance of USDT stablecoin.'),
  nftaHoldings: z
    .array(
      z.object({
        nodeId: z.string().describe('Unique identifier for the NFTA node.'),
        yieldPerDay: z.number().describe('Daily TOT yield generated by this NFTA node.'),
      })
    )
    .describe('Details of NFTA node holdings, including daily TOT yield.'),
  nftbHoldings: z
    .array(
      z.object({
        nodeId: z.string().describe('Unique identifier for the NFTB node.'),
        level: z.number().describe('Level of the NFTB node.'),
        weight: z.number().describe('Weight of the NFTB node.'),
        historicalDividends: z
          .array(
            z.object({
              date: z.string().describe('Date of dividend distribution (YYYY-MM-DD).'),
              totAmount: z.number().describe('Amount of TOT received as dividend.'),
              usdtAmount: z.number().describe('Amount of USDT received as dividend.'),
            })
          )
          .describe('Historical dividend distributions for this NFTB node.'),
      })
    )
    .describe(
      'Details of NFTB node holdings, including level, weight, and historical dividend distributions.'
    ),
  predictionMarketHistory: z
    .array(
      z.object({
        platform: z.string().describe('Name of the prediction platform.'),
        predictionId: z.string().describe('Unique identifier for the prediction.'),
        outcome: z.string().describe('Predicted outcome.'),
        stake: z.number().describe('Amount staked.'),
        winnings: z.number().describe('Amount won (0 if lost).'),
        date: z.string().describe('Date of prediction (YYYY-MM-DD).'),
      })
    )
    .describe(
      'History of user participation in prediction markets, including platform, outcome, stake, and winnings.'
    ),
});
export type AiPoweredYieldInsightInput = z.infer<typeof AiPoweredYieldInsightInputSchema>;

const AiPoweredYieldInsightOutputSchema = z.object({
  overallSummary: z
    .string()
    .describe('An overall summary of the user\'s current DeFi portfolio and performance.'),
  totYieldStrategy: z.string().describe('Recommended strategies to optimize TOT yield.'),
  tofYieldStrategy: z.string().describe('Recommended strategies to optimize TOF yield.'),
  potentialEarningsEstimation: z
    .string()
    .describe('An estimation of potential earnings based on the suggested strategies.'),
  actionableInsights: z.array(z.string()).describe('A list of actionable steps the user can take.'),
});
export type AiPoweredYieldInsightOutput = z.infer<typeof AiPoweredYieldInsightOutputSchema>;

const prompt = ai.definePrompt({
  name: 'aiPoweredYieldInsightPrompt',
  input: {schema: AiPoweredYieldInsightInputSchema},
  output: {schema: AiPoweredYieldInsightOutputSchema},
  prompt: `You are a highly intelligent and experienced DeFi investment strategist. Your goal is to provide personalized, AI-generated strategies for optimizing TOT/TOF yield and potential earnings for a DeFi investor.

IMPORTANT: You must provide the analysis in the language specified below.
Preferred Language: {{{language}}} (If 'zh', respond in Chinese. If 'en', respond in English).

Analyze the provided user data, including NFT holdings, token balances, and prediction market activity, to identify opportunities and risks. Then, recommend clear, actionable strategies.

User Wallet Address: {{{walletAddress}}}

Current Token Balances:
- TOT: {{{totBalance}}}
- TOF: {{{tofBalance}}}
- USDT: {{{usdtBalance}}}

NFTA Node Holdings:
{{#if nftaHoldings}}
{{#each nftaHoldings}}
  - Node ID: {{{nodeId}}}, Daily TOT Yield: {{{yieldPerDay}}}
{{/each}}
{{else}}
  No NFTA holdings.
{{/if}}

NFTB Node Holdings:
{{#if nftbHoldings}}
{{#each nftbHoldings}}
  - Node ID: {{{nodeId}}}, Level: {{{level}}}, Weight: {{{weight}}}
    Historical Dividends:
    {{#if historicalDividends}}
    {{#each historicalDividends}}
      - Date: {{{date}}}, TOT: {{{totAmount}}}, USDT: {{{usdtAmount}}}
    {{/each}}
    {{else}}
      No historical dividends for this NFTB node.
    {{/if}}
{{/each}}
{{else}}
  No NFTB holdings.
{{/if}}

Prediction Market Participation History:
{{#if predictionMarketHistory}}
{{#each predictionMarketHistory}}
  - Platform: {{{platform}}}, Prediction ID: {{{predictionId}}}, Outcome: {{{outcome}}}, Stake: {{{stake}}}, Winnings: {{{winnings}}}, Date: {{{date}}}
{{/each}}
{{else}}
  No prediction market history.
{{/if}}

Based on the above information, provide a comprehensive analysis and strategy. Ensure your recommendations are specific, practical, and tailored to maximize TOT/TOF yield and potential earnings.`,
});

export async function aiPoweredYieldInsight(
  input: AiPoweredYieldInsightInput
): Promise<AiPoweredYieldInsightOutput> {
  try {
    const {output} = await prompt(input);
    if (!output) throw new Error('AI failed to generate a response');
    return output;
  } catch (error) {
    console.error('Error in aiPoweredYieldInsight flow:', error);
    // Return a graceful fallback if the AI key is missing or service is down
    return {
      overallSummary: "We are currently experiencing issues connecting to the AI analysis engine. Please ensure your environment variables are configured correctly.",
      totYieldStrategy: "Maintain current staking levels.",
      tofYieldStrategy: "Accumulate TOF for future node upgrades.",
      potentialEarningsEstimation: "Analysis unavailable.",
      actionableInsights: ["Verify GEMINI_API_KEY", "Try again in a few minutes"]
    };
  }
}
